apiVersion: v1
kind: Pod
metadata:
  name: kata-test
spec:
  runtimeClassName: kata-cloud-hypervisor
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox:latest
    command: ["echo", "Hello"]
