apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mirror
  labels:
    service: mirror
spec:
  containers:
  - name: app
    imagePullPolicy: Never
    image: localhost/simple-git-http-server
    command:
    - sh
    - -c
    - |
      set -euo pipefail

      cd /git
      if [ ! -d kubernetes.git ]; then
        git clone --bare https://github.com/kubernetes/kubernetes.git --depth 50
      fi
      cd kubernetes.git
      git update-server-info

      cd /
      spawn-fcgi -s /run/fcgi.sock -U nginx /usr/bin/fcgiwrap
      nginx -g "daemon off;"
    volumeMounts:
    - name: fs
      mountPath: /git
  volumes:
  - name: fs
    persistentVolumeClaim:
      claimName: mirror
---
apiVersion: v1
kind: Service
metadata:
  name: mirror
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    service: mirror
