---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-fs-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-fs-pvc-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-block-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: fs-test-kata
spec:
  runtimeClassName: kata-qemu
  containers:
  - name: app
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command:
    - bash
    - -c
    - |
      mkdir -p /blk
      mkfs.ext4 /dev/xvda
      mount /dev/xvda /blk

      sleep Infinity
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
    volumeMounts:
    - name: fs
      mountPath: /data
    volumeDevices:
    - name: blk
      devicePath: /dev/xvda
  volumes:
  - name: blk
    persistentVolumeClaim:
      claimName: my-block-pvc-2
  - name: fs
    persistentVolumeClaim:
      claimName: my-fs-pvc-2
---
apiVersion: v1
kind: Pod
metadata:
  name: fs-test-gvisor
spec:
  runtimeClassName: gvisor
  containers:
  - name: app
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command:
    - bash
    - -c
    - sleep Infinity
    volumeMounts:
    - name: fs
      mountPath: /data
    - name: tmp
      mountPath: /tmp
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
  volumes:
  - name: fs
    persistentVolumeClaim:
      claimName: my-fs-pvc-3
  - name: tmp
    emptyDir:
      medium: Memory
      sizeLimit: 8Gi
